import React,{useEffect,useRef,useState} from 'react';
import {model} from '../lib/model';
import {platform} from '../lib/platform';
import {Action,Box,Field,Label,Picker,Shell,Sheet} from './Surface';
type Entry=ReturnType<typeof model.blank>;
type State=ReturnType<typeof model.empty>;
const categories=[['Court','⚖','Court & Legal'],['Medical','♥','Medical & Safety'],['Visit','♟','Visits'],['Timeline','◷','Timeline'],['Document','▣','Documents'],['Help','?','Get Help']];
const topicNotes:Record<string,string>={
  'Medical treatment':'Record the concern, when it started, who you contacted and their response. Use Medical & Safety to keep the follow-up together.',
  'Court / bail':'Keep hearing notices, dates, matter numbers and solicitor details together. Confirm dates and advice directly with your legal representative.',
  'Safety or assault':'Keep a dated account of what was reported, the source and whom you contacted. Save a follow-up record; recording here does not notify anyone.',
  'Contact and visits':'Keep the centre’s contact details, booking references, visitor approvals and the outcome of each call in your records.',
  'Money / property':'Keep receipts, transaction references and a dated record of any request or response.',
  'Documents':'Keep your original documents and an independent backup. Use the document wallet for copies on this device or browser.',
  'Make a complaint':'Write a factual chronology, the people or service contacted, their response and the outcome you are requesting. Save relevant correspondence.',
  'Preparing for release':'Use visit or note records for transport, accommodation, appointments, medications and contact arrangements that need confirmation.'
};
export default function Organiser({initialPage='Home'}:{initialPage?:string}) {
  const [state,setState]=useState<State>(model.empty()); const current=useRef(state);
  const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false); const writing=useRef(false);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [page,setPage]=useState(initialPage);
  const [filter,setFilter]=useState('All');const [search,setSearch]=useState('');const [edit,setEdit]=useState<Entry|null>(null);
  const [profile,setProfile]=useState<State['profile']|null>(null);const [confirm,setConfirm]=useState<'clear'|Entry|null>(null);
  const [topic,setTopic]=useState('');
  useEffect(()=>{let active=true;platform.load().then(s=>{if(active){current.current=s;setState(s);setReady(true);}}).catch(e=>{if(active)setError('Unable to load saved records: '+e.message);});return()=>{active=false;};},[]);
  async function work(fn:()=>Promise<void>){if(writing.current)return;writing.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'The action could not be completed.');}finally{writing.current=false;setBusy(false);}}
  async function commit(s:State){await platform.save(s);current.current=s;setState(s);}
  function go(p:string){setPage(p);setFilter('All');setSearch('');setNotice('');}
  function add(kind=page){setEdit(model.blank(model.kinds.includes(kind)?kind:'Note'));setError('');}
  async function saveEntry(){if(!edit)return;const problem=model.validate(edit);if(problem){setError(problem);return;}await work(async()=>{let item={...edit,title:edit.title.trim()};const old=current.current.entries.find(e=>e.id===item.id);if(old?.reminderId&&(old.date!==item.date||old.time!==item.time||item.status==='Completed')){await platform.cancelReminder(old.reminderId);item.reminderId=undefined;}await commit({...current.current,entries:[...current.current.entries.filter(e=>e.id!==item.id),item]});setEdit(null);setNotice('Record saved.');});}
  async function deleteConfirmed(){await work(async()=>{if(confirm==='clear'){for(const e of current.current.entries){if(e.reminderId)await platform.cancelReminder(e.reminderId);if(e.attachment)await platform.removeAttachment(e.attachment);}await commit(model.empty());setNotice('Organiser data cleared.');}else if(confirm){if(confirm.reminderId)await platform.cancelReminder(confirm.reminderId);if(confirm.attachment)await platform.removeAttachment(confirm.attachment);await commit({...current.current,entries:current.current.entries.filter(e=>e.id!==confirm.id)});setNotice('Record removed.');}setConfirm(null);});}
  async function attach(files:any[]){await work(async()=>{for(const file of files){const attachment=await platform.attach(file);const entry={...model.blank('Document'),title:String(file.name||'Document').slice(0,200),status:'Completed',attachment};try{await commit({...current.current,entries:[...current.current.entries,entry]});}catch(e){await platform.removeAttachment(attachment);throw e;}}setNotice('Document copies saved here.');});}
  const entries=model.sort(state.entries);
  const visible=entries.filter(e=>(page==='Timeline'||e.kind===page)&&(filter==='All'||e.kind===filter||e.status===filter)&&`${e.title} ${e.place} ${e.details}`.toLowerCase().includes(search.toLowerCase()));
  const issues=entries.filter(e=>['Follow up','Missing','Not confirmed'].includes(e.status));
  const court=model.next(state,'Court');const visit=model.next(state,'Visit');
  const nav=<Box variant="navBar">{[['Home','⌂'],['Timeline','◷'],['Add','＋'],['Call','☎'],['More','•••']].map(([p,icon])=><Action key={p} disabled={!ready||busy} tone={page===p?'selected':'nav'} onPress={()=>p==='Add'?add('Note'):go(p)}>{icon}{'\n'}{p==='Call'?'Calls':p}</Action>)}</Box>;
  if(!ready)return <Shell nav={null}><Label variant="title">Inside & Out</Label><Label>{error||'Loading your organiser…'}</Label></Shell>;
  return <Shell nav={nav}>
    <Box variant="row"><Box><Label variant="title">{page==='Home'?'Inside & Out':categories.find(c=>c[0]===page)?.[2]|| (page==='Call'?'Calls & Follow-ups':page)}</Label><Label variant="accent">{page==='Home'?'Support that stays with you.':'Your family organiser'}</Label></Box>{page!=='Home'&&<Action tone="quiet" onPress={()=>go('Home')}>Home</Action>}</Box>
    {state.demo&&<Box variant="alert"><Label variant="badge">SAMPLE DATA</Label><Label variant="small">These are fictional examples. Clear sample data in More before adding personal records.</Label></Box>}
    {!!error&&<Label variant="error">{error}</Label>}{!!notice&&<Label variant="accent">{notice}</Label>}
    {page==='Home'&&<>
      <Box variant="hero"><Label variant="heading">{state.profile.name||'Your support circle starts here'}</Label><Label variant="small">{state.profile.min?`MIN: ${state.profile.min}`:'Add a name and optional MIN'}</Label><Label>{state.profile.location||'Keep important details together.'}</Label><Action tone="quiet" onPress={()=>setProfile({...state.profile})}>Edit profile</Action></Box>
      {issues.length>0&&<Box variant="alert"><Label variant="badge">NEEDS FOLLOW-UP · {issues.length}</Label><Label variant="heading">{issues[0].title}</Label><Label variant="small">{issues[0].date} · {issues[0].status}</Label><Action tone="quiet" onPress={()=>{go(issues[0].kind);setEdit({...issues[0]});}}>View record</Action></Box>}
      <Box variant="card">{[['Next court date',court?`${court.date} ${court.time}`:'No upcoming date','Court'],['Next visit',visit?`${visit.date} ${visit.time}`:'No upcoming visit','Visit'],['Open follow-ups',String(issues.length),'Timeline'],['Documents',String(entries.filter(e=>e.kind==='Document').length),'Document'],['Last call',entries.find(e=>e.kind==='Call')?.date||'No calls recorded','Call']].map(([label,value,p])=><Box variant="row" key={label}><Box><Label variant="small">{label}</Label><Label variant="heading">{value}</Label></Box><Action tone="quiet" onPress={()=>go(p)}>View</Action></Box>)}</Box>
      <Box variant="grid">{categories.map(([p,icon,label])=><Action key={p} tone="tile" onPress={()=>go(p)}>{icon}{'\n'}{label}</Action>)}</Box>
      {!entries.length&&!state.profile.name&&<Action tone="quiet" disabled={busy} onPress={()=>work(async()=>{await commit(model.sample());})}>Explore sample records</Action>}
    </>}
    {(model.kinds.includes(page)||page==='Timeline')&&<>
      {page==='Medical'&&<Label variant="small">Record medications, conditions and incidents. Notes are not sent to a clinician or emergency service.</Label>}
      {page==='Court'&&<Label variant="small">Keep matter numbers, charges as entered, solicitor details and bail preparation notes with each court record.</Label>}
      {page==='Visit'&&<Label variant="small">Keep visitor names, approval status, booking references and transport notes together. Adding a record does not book a visit.</Label>}
      {page==='Document'?<><Label variant="small">Copies stay on this device or browser. JSON exports contain record metadata, not the document files. Keep original documents separately.</Label>{platform.native?<Action disabled={busy} onPress={()=>platform.pick().then(attach).catch(e=>setError(e.message))}>Choose documents</Action>:<Picker disabled={busy} onPick={attach}/>}</>:<Action tone={page==='Medical'?'danger':'teal'} disabled={busy} onPress={()=>add()}>+ {page==='Medical'?'Add medication, condition or incident':page==='Timeline'?'Add event':'Add record'}</Action>}
      <Field label="Search records" value={search} onChange={setSearch} placeholder="Title, location or notes"/>
      <Box variant="grid">{(page==='Timeline'?['All',...model.kinds]:['All','Follow up','Completed']).map(t=><Action key={t} tone={filter===t?'selected':'quiet'} onPress={()=>setFilter(t)}>{t}</Action>)}</Box>
      {visible.length===0&&<Box variant="card"><Label variant="heading">{entries.some(e=>page==='Timeline'||e.kind===page)?'No matching records':'Nothing saved yet'}</Label><Label variant="small">{search?'Try another search.':'Add a record to begin. Your saved entries will appear here.'}</Label></Box>}
      {visible.map(e=><Box variant="card" key={e.id}><Label variant="badge">{e.kind} · {e.status}</Label><Label variant="heading">{e.title}</Label><Label variant="small">{e.date}{e.time?' · '+e.time:''}{e.place?' · '+e.place:''}</Label>{!!e.details&&<Label>{e.details}</Label>}<Box variant="row"><Action tone="quiet" disabled={busy} onPress={()=>{setError('');setEdit({...e});}}>Edit</Action>{e.attachment&&<Action tone="quiet" disabled={busy} onPress={()=>work(async()=>{await platform.open(e.attachment!);})}>Open / share</Action>}<Action tone="quiet" disabled={busy} onPress={()=>setConfirm(e)}>Delete</Action></Box>{platform.native&&e.kind!=='Document'&&e.status!=='Completed'&&<Action tone="quiet" disabled={busy} onPress={()=>work(async()=>{if(e.reminderId){await platform.cancelReminder(e.reminderId);await commit({...current.current,entries:current.current.entries.map(x=>x.id===e.id?{...x,reminderId:undefined}:x)});setNotice('Reminder cancelled.');}else{const id=await platform.remind(e);try{await commit({...current.current,entries:current.current.entries.map(x=>x.id===e.id?{...x,reminderId:id}:x)});}catch(error){await platform.cancelReminder(id);throw error;}setNotice('Reminder scheduled for '+e.date+' '+(e.time||'09:00')+'.');}})}>{e.reminderId?'Cancel reminder':'Remind me at this time'}</Action>}</Box>)}
      {page==='Timeline'&&<Action tone="quiet" disabled={busy} onPress={()=>work(async()=>{await platform.export({...state,entries:visible});})}>Export displayed timeline</Action>}
    </>}
    {page==='Help'&&<><Label variant="heading">What do you need help with?</Label><Box variant="grid">{Object.keys(topicNotes).map(t=><Action key={t} tone="tile" onPress={()=>setTopic(t)}>{t}</Action>)}</Box><Box variant="card"><Label variant="heading">Keep a clear record</Label><Label>Save dates, documents and the outcome of each call so your next conversation is easier.</Label><Action tone="teal" onPress={()=>{go('Note');add('Note');}}>Write a note</Action></Box></>}
    {page==='More'&&<><Box variant="card"><Label variant="heading">Your data</Label><Label>{platform.storageNote}</Label>{!platform.native&&<Label variant="small">This browser version has no app lock. Use a private device. Clearing browser data can remove saved records and files. Native Face ID and reminders are only in the mobile build.</Label>}<Action disabled={busy} onPress={()=>work(async()=>{await platform.export(state);})}>Export organiser backup</Action><Action disabled={busy} tone="danger" onPress={()=>setConfirm('clear')}>{state.demo?'Clear sample data':'Delete organiser data'}</Action></Box><Box variant="card"><Label variant="heading">About Inside & Out</Label><Label>A family organiser for court, medical, visits, calls and documents.</Label><Label variant="small">Mobile and Floot records are separate. There are no user accounts, automatic family sharing or live government feeds in this version.</Label></Box></>}
    <Label variant="small">Organisational tools only. Not connected to Corrective Services, courts, hospitals or emergency services. For urgent help, contact the relevant service directly.</Label>
    <Sheet open={!!edit} title={edit&&entries.some(e=>e.id===edit.id)?'Edit record':'Add record'} onClose={()=>{if(!busy)setEdit(null);}}>{edit&&<><Label variant="small">Category</Label><Box variant="grid">{model.kinds.filter(k=>edit.attachment?k==='Document':k!=='Document').map(k=><Action key={k} tone={edit.kind===k?'selected':'quiet'} disabled={busy} onPress={()=>setEdit({...edit,kind:k})}>{k}</Action>)}</Box><Field label={edit.kind==='Medical'?'Medication, condition or incident':'Title'} value={edit.title} onChange={title=>setEdit({...edit,title})}/><Field label="Date (YYYY-MM-DD)" placeholder="2026-09-12" value={edit.date} onChange={date=>setEdit({...edit,date})}/><Field label="Time (HH:MM, 24-hour, optional)" placeholder="09:30" value={edit.time} onChange={time=>setEdit({...edit,time})}/><Field label="Location / organisation" value={edit.place} onChange={place=>setEdit({...edit,place})}/><Field label={edit.kind==='Medical'?'Dose, frequency, source and notes':'Details, contacts and reference numbers'} multiline value={edit.details} onChange={details=>setEdit({...edit,details})}/><Label variant="small">Status</Label><Box variant="grid">{model.statuses.map(status=><Action key={status} tone={edit.status===status?'selected':'quiet'} onPress={()=>setEdit({...edit,status})}>{status}</Action>)}</Box>{!!error&&<Label variant="error">{error}</Label>}<Action disabled={busy} tone="teal" onPress={saveEntry}>{busy?'Saving…':'Save record'}</Action></>}</Sheet>
    <Sheet open={!!profile} title="Profile" onClose={()=>{if(!busy)setProfile(null);}}>{profile&&<><Field label="Name" value={profile.name} onChange={name=>setProfile({...profile,name})}/><Field label="MIN (optional)" value={profile.min} onChange={min=>setProfile({...profile,min})}/><Field label="Location" value={profile.location} onChange={location=>setProfile({...profile,location})}/>{!!error&&<Label variant="error">{error}</Label>}<Action disabled={busy} onPress={()=>work(async()=>{await commit({...current.current,profile});setProfile(null);setNotice('Profile saved.');})}>Save profile</Action></>}</Sheet>
    <Sheet open={!!confirm} title="Confirm deletion" onClose={()=>{if(!busy)setConfirm(null);}}><Label>{confirm==='clear'?'Delete your organiser profile, records and attached copies here? This cannot be undone. Save a backup and original documents first. Your native app-lock credentials are kept.':'Delete this record and its attached copy? This cannot be undone.'}</Label>{!!error&&<Label variant="error">{error}</Label>}<Action tone="danger" disabled={busy} onPress={deleteConfirmed}>Delete permanently</Action></Sheet>
    <Sheet open={!!topic} title={topic||'Help'} onClose={()=>setTopic('')}><Label>{topicNotes[topic]}</Label><Action onPress={()=>{setTopic('');go('Note');add('Note');}}>Add a note</Action></Sheet>
  </Shell>;
}
