import React from 'react';
import {View,Text,TextInput,Pressable,ScrollView,Modal,StyleSheet,KeyboardAvoidingView,Platform,Switch} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
const c={navy:'#173A54',teal:'#174F4B',tealMid:'#218A84',muted:'#60727E',line:'#E1E8E7',ivory:'#FAF8F3',aqua:'#D9F3F1'};
export function Box({children,variant='stack'}:{children?:React.ReactNode;variant?:string}){return <View style={(styles as any)[variant]||styles.stack}>{children}</View>}
export function Label({children,variant='body'}:{children?:React.ReactNode;variant?:string}){return <Text accessibilityRole={variant==='title'?'header':undefined} style={(styles as any)[variant]||styles.body}>{children}</Text>}
export function Action({children,onPress,tone='primary',disabled=false}:{children:React.ReactNode;onPress:()=>void;tone?:string;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.action,(styles as any)[tone],disabled&&{opacity:.45}]}><Text style={[styles.actionText,['quiet','tile','nav','selected'].includes(tone)&&{color:c.navy}]}>{children}</Text></Pressable>}
export function Field({label,value,onChange,multiline=false,placeholder=''}:{label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;placeholder?:string}){return <View style={styles.stack}><Text style={styles.small}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} multiline={multiline} style={[styles.field,multiline&&{minHeight:100,textAlignVertical:'top'}]} /></View>}
export function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(b:boolean)=>void}){return <View style={styles.row}><Text style={styles.body}>{label}</Text><Switch accessibilityLabel={label} value={value} onValueChange={onChange}/></View>}
export function Shell({children,nav}:{children:React.ReactNode;nav:React.ReactNode}){return <SafeAreaView style={styles.shell}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{children}</ScrollView>{nav}</SafeAreaView>}
export function Sheet({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:React.ReactNode}){return <Modal visible={open} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.shell}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Label variant="title">{title}</Label>{children}<Action tone="quiet" onPress={onClose}>Cancel</Action></ScrollView></KeyboardAvoidingView></SafeAreaView></Modal>}
export const Picker = (_:{onPick:(files:any[])=>void;disabled?:boolean})=>null;
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:c.ivory},content:{paddingHorizontal:20,paddingTop:14,paddingBottom:34,gap:16,width:'100%',maxWidth:430,alignSelf:'center'},stack:{gap:8},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,flexWrap:'wrap'},grid:{flexDirection:'row',gap:10,flexWrap:'wrap'},card:{borderWidth:1,borderColor:c.line,borderRadius:22,padding:17,gap:10,backgroundColor:'#FFFEFB',shadowColor:'#173A54',shadowOpacity:.045,shadowRadius:14,shadowOffset:{width:0,height:5}},alert:{borderRadius:20,padding:16,gap:7,backgroundColor:'#FBECEE'},hero:{backgroundColor:c.aqua,borderRadius:24,padding:20,gap:8},navBar:{flexDirection:'row',justifyContent:'space-around',borderTopWidth:1,borderTopColor:c.line,paddingHorizontal:6,paddingTop:7,paddingBottom:5,backgroundColor:'#FFFEFB'},title:{fontSize:28,fontWeight:'900',color:c.navy,letterSpacing:-.7},heading:{fontSize:18,fontWeight:'800',color:c.navy,lineHeight:23},body:{fontSize:14,lineHeight:21,color:c.navy},small:{fontSize:12.5,lineHeight:18,color:c.muted},accent:{fontSize:13.5,fontWeight:'800',color:c.tealMid},error:{fontSize:14,color:'#9D253C'},badge:{fontSize:11,color:c.teal,fontWeight:'900',letterSpacing:.8},action:{borderRadius:14,paddingHorizontal:15,paddingVertical:13,backgroundColor:c.navy,alignItems:'center',justifyContent:'center',minHeight:46},actionText:{color:'#fff',fontSize:14,fontWeight:'800',textAlign:'center'},quiet:{backgroundColor:'#EFF4F4'},teal:{backgroundColor:c.teal},danger:{backgroundColor:'#A33248'},tile:{backgroundColor:'#E8F3F1',width:'31%',minHeight:94,justifyContent:'center'},nav:{backgroundColor:'#FFFEFB',paddingHorizontal:7},selected:{backgroundColor:c.aqua,paddingHorizontal:7},field:{borderWidth:1,borderColor:'#C8D5D4',borderRadius:14,padding:13,fontSize:16,color:c.navy,backgroundColor:'#FFFEFB'}});
