import React from 'react';
import {View,Text,TextInput,Pressable,ScrollView,Modal,StyleSheet,KeyboardAvoidingView,Platform,Switch} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
const c={navy:'#17364D',teal:'#207E7B',muted:'#566976',line:'#E7ECEF'};
export function Box({children,variant='stack'}:{children?:React.ReactNode;variant?:string}){return <View style={(styles as any)[variant]||styles.stack}>{children}</View>}
export function Label({children,variant='body'}:{children?:React.ReactNode;variant?:string}){return <Text accessibilityRole={variant==='title'?'header':undefined} style={(styles as any)[variant]||styles.body}>{children}</Text>}
export function Action({children,onPress,tone='primary',disabled=false}:{children:React.ReactNode;onPress:()=>void;tone?:string;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.action,(styles as any)[tone],disabled&&{opacity:.45}]}><Text style={[styles.actionText,['quiet','tile','nav','selected'].includes(tone)&&{color:c.navy}]}>{children}</Text></Pressable>}
export function Field({label,value,onChange,multiline=false,placeholder=''}:{label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;placeholder?:string}){return <View style={styles.stack}><Text style={styles.small}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} multiline={multiline} style={[styles.field,multiline&&{minHeight:100,textAlignVertical:'top'}]} /></View>}
export function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(b:boolean)=>void}){return <View style={styles.row}><Text style={styles.body}>{label}</Text><Switch accessibilityLabel={label} value={value} onValueChange={onChange}/></View>}
export function Shell({children,nav}:{children:React.ReactNode;nav:React.ReactNode}){return <SafeAreaView style={styles.shell}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>{children}</ScrollView>{nav}</SafeAreaView>}
export function Sheet({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:React.ReactNode}){return <Modal visible={open} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.shell}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Label variant="title">{title}</Label>{children}<Action tone="quiet" onPress={onClose}>Cancel</Action></ScrollView></KeyboardAvoidingView></SafeAreaView></Modal>}
export const Picker = (_:{onPick:(files:any[])=>void;disabled?:boolean})=>null;
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:'#fff'},content:{padding:20,paddingBottom:30,gap:14,width:'100%',maxWidth:680,alignSelf:'center'},stack:{gap:8},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,flexWrap:'wrap'},grid:{flexDirection:'row',gap:8,flexWrap:'wrap'},card:{borderWidth:1,borderColor:c.line,borderRadius:18,padding:16,gap:9,backgroundColor:'#fff'},alert:{borderRadius:18,padding:16,gap:7,backgroundColor:'#FDECEF'},hero:{backgroundColor:'#DDF5F2',borderRadius:20,padding:20,gap:8},navBar:{flexDirection:'row',justifyContent:'space-around',borderTopWidth:1,borderTopColor:c.line,padding:6,backgroundColor:'#fff'},title:{fontSize:25,fontWeight:'900',color:c.navy},heading:{fontSize:18,fontWeight:'800',color:c.navy},body:{fontSize:14,lineHeight:21,color:c.navy},small:{fontSize:12,lineHeight:18,color:c.muted},accent:{fontSize:13,fontWeight:'700',color:c.teal},error:{fontSize:14,color:'#9D253C'},badge:{fontSize:12,color:c.teal,fontWeight:'800'},action:{borderRadius:14,paddingHorizontal:15,paddingVertical:13,backgroundColor:c.navy,alignItems:'center',minHeight:44},actionText:{color:'#fff',fontSize:14,fontWeight:'700',textAlign:'center'},quiet:{backgroundColor:'#F2F6F8'},teal:{backgroundColor:c.teal},danger:{backgroundColor:'#A33248'},tile:{backgroundColor:'#E8F3F3',width:'31%',minHeight:85,justifyContent:'center'},nav:{backgroundColor:'#fff',paddingHorizontal:7},selected:{backgroundColor:'#DDF5F2',paddingHorizontal:7},field:{borderWidth:1,borderColor:'#CAD5DD',borderRadius:12,padding:12,fontSize:16,color:c.navy,backgroundColor:'#fff'}});
